[build]
builder = "DOCKERFILE"
dockerfilePath = "openbb-sidecar/Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/v1/user"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
